# Universal Functions: Fast Element-Wise Array Functions

A universal function, or *ufunc*, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results. 

Many ufuncs are simple element-wise transformations, like ``numpy.sqrt`` or ``numpy.exp``:

In [1]:
import numpy as np 

arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [3]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

These are reffered to as *unary* ufuncs. Others, such as ``numpy.add`` or ``numpy.maxium``, take two arrays (thus, *binary* ufuncs) and return a single array as the result:

In [8]:
import numpy as np

x = np.random.standard_normal(8)

y = np.random.standard_normal(8)

In [5]:
x, y

(array([ 0.99578056, -0.04948529, -0.02571428, -0.92147893, -0.5878167 ,
         0.56293047,  0.02223715, -0.82419186]),
 array([ 1.46879198, -1.44803672,  0.2353895 ,  1.44873091, -0.46769295,
        -0.22302025,  0.37217479, -1.55532981]))

In [6]:
np.maximum(x, y)

array([ 1.46879198, -0.04948529,  0.2353895 ,  1.44873091, -0.46769295,
        0.56293047,  0.37217479, -0.82419186])

While not common, a ufunc can return multiple arrays. ``numpy.modf`` is one example: 

a vectorized version of the built-in Python ``math.modf``, it returns the fractional and integer parts of a floating point array:

In [10]:
arr = np.random.standard_normal(7)*5

arr

array([ 5.01248108, -6.27383517, -2.17192286,  0.99968725, -0.57851329,
       -2.27682576,  6.66104006])

In [12]:
remainder, whole_part = np.modf(arr)

remainder


array([ 0.01248108, -0.27383517, -0.17192286,  0.99968725, -0.57851329,
       -0.27682576,  0.66104006])

In [13]:
whole_part

array([ 5., -6., -2.,  0., -0., -2.,  6.])