One of the key features of NumPy is its N-dimensional array object, or ndarray, which is fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements. 

To give a flavor of how NumPy enables batch computations with similar syntax to scalar values on built-in Python objects, import NumPy and create a small array:


In [86]:
import numpy as np 

data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])

data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

You can write mathematical operations with data:

In [87]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [88]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In the first example, all of the elements have been multiplied by 10. In the second, the corresponding values in each "cell" in the array have been added to each other. 


An ndarray is a generic multidimensional container for homogenous data, that is, all of the elements must be the same type. Every array has a ``shape``, a tuple indicating the size of each dimension, and a ``dtype``, an object describing the *data type* of the array:

In [89]:
data.shape 

(2, 3)

In [90]:
data.dtype

dtype('float64')

## Creating ndarrays

The easiest way to create an array is to use the ``array`` function. This accepts any sequence-like object (including other arrays) and produces a new NumPy array containing the passed data. For example, a list is a good candidate for converison:

In [91]:
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)


arr1

array([6. , 7.5, 8. , 0. , 1. ])

Nested sequences, like a list of equal-lengths lists, will be converted into a multidimensional array:

In [92]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2  = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Since ``data2`` was a list of lists, the NumPy array ``arr2`` has two dimensions, with shape inferred from the data. We can confirm this by inspecting the ``ndim`` and ``shape`` atributes. 

In [93]:
arr2.ndim

2

In [94]:
arr2.shape

(2, 4)

Unless explicitly specified, ```numpy.array``` tries to infer a good data type for the array that it creates. The data type is stored in a special ``dtype`` metadata object; for example, in the previous two example we have:

In [95]:
arr1.dtype

dtype('float64')

In [96]:
arr2.dtype

dtype('int64')

In addition to ``numpy.array``, there are a number of other functions for creating new arrays. As examples, ``numpy.zeros`` and ``numpy.ones`` create arrays of 0s and 1s, with a given length or shape. 

``numpy.empty`` creates an array without initialzing its value to any particular value. To create a higher dimensional array with these methods, pass a tuple for the shape: 

In [97]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [98]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [99]:
np.empty((2, 3, 2))

array([[[5., 5.],
        [5., 5.],
        [3., 3.]],

       [[3., 3.],
        [1., 1.],
        [1., 1.]]])

``numpy.array`` is an array-valued version of the built-in Python ``range`` function:

In [100]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [101]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Data types for ndarrays

The *data type* or ``dtype`` is a special object containing the information (or *metadata*, data about data) the ndarray needs to interpret a chunk of memory as a particular type of data:

In [102]:
arr1 = np.array([1, 2, 3], dtype = np.float64)

arr = np.array([1, 2, 3], dtype =np.int32 )

In [103]:
arr1.dtype

dtype('float64')

In [104]:
arr2.dtype

dtype('int64')

Data types are a source of NumPy's flexibility for interacting with data coming from other systems. In most cases they provide a mapping directly onto an underlying disk or memory representation, which makes it possible to read and write binary streams of data to disk and to connect to code written in low-level language like C or FORTRAN. The numerical data types are named the same way: a type name, like ``float`` or ``int``, followed by a number indicating the number of bits per element. A standard double-precision floating-point value (what's used under the hood in Python's ``float`` object) takes up to 8 bytes or 64 bits. Thus, this type is known in NumPy as ``float64``. 


You can explicitly convert or *cast* an array from one data type to another using ndarray's ``astype`` method:


In [105]:
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int64')

In [106]:
float_arr = arr.astype(np.float64)

float_arr

array([1., 2., 3., 4., 5.])

In [107]:
float_arr.dtype

dtype('float64')

In this example integers were cast to floating point. Casting some floating-point numbers to be of integer data type, the decimal part will be truncated:

In [108]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

arr 


array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [109]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

If you have an array of strings representing numbers, you can use ``astype`` to convert them to numeric form:

In [110]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype = np.bytes_)

numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [111]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

If casting were to fail for some reason (like a string that cannot be converted to ``float64``), a ``ValueError`` will be raised. 

You can also use another array's ``dtype`` attribute:

In [112]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)


In [113]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

There are shorthand type code strings you can also use to refer to a ``dtype``:

In [114]:
zeros_unit32 = np.zeros(8, dtype="u4")

zeros_unit32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

>**Note**: calling ``astype`` *always* creates a new array (a copy of the data) even if the new data is the same as the old data type. 

## Arithmetic with NumPy Arrays

Arrays are important because they enable you to express batch operations on data without writing any ``for loops``. NumPy users call this *vectorization*. Any arithmetic operations between equal-size arrays apply the operaton element-wise:

In [115]:
arr = np.array([[1., 2., 3.,], [4., 5., 6.]])

arr 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [116]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [117]:
arr - arr 

array([[0., 0., 0.],
       [0., 0., 0.]])

Arithmetic operations with scalars propagate the scalar argument to each element in the array:

In [118]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [119]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

**Comparisons** between the arrays of the same size yield ``Boolean`` arrays:

In [120]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [121]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

Evaluating operations between differently sized arrays is called *broadcasting*. 

## Basic Indexing and Slicing

NumPy array indexing is a deep topic, as there are many ways you may want to select a subset of your data or individual elements. One-dimensional arrays are simple; on the surface they act similarly to Python lists:

In [122]:
arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
arr[5]

np.int64(5)

In [124]:
arr[5:8]

array([5, 6, 7])

In [125]:
arr[5:8] = 12

arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

If you assign a scalar value to a slice, as in ``arr[5:8]`` = 12, the value is propagated (or *broadcast* henceforth) to the entire selection. 

For example:

In [126]:
arr_slice = arr[5:8]

arr_slice

array([12, 12, 12])

In [127]:
arr_slice[1] = 12345

arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

The "bare" slice ``[:]`` will assign to all values in an array:

In [128]:
arr_slice[:] = 64

arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays:

In [129]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[2]

array([7, 8, 9])

Thus, individual elements can be accessed recursively. But that is a bit too much work, so you can pass a comma-seperated list of indices to select individual elements. So these are equivalent:

In [130]:
arr2d[0][2]

np.int64(3)

In [131]:
arr2d[0,2]

np.int64(3)

In multidimensional arrays, if you omit later indices, the returned object will be a lower dimensional ndarray consisting of all the data along the higher dimensions. So in the 2x2x3 array ``arr3d``

In [132]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [133]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

## Indexing with slices

Like one-dimensional objects such as Python lists, ndarrays can be sliced  with the familiar syntax:

In [134]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [135]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [136]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

As you can see, it has sliced along axis 0, the first axis. A slice, therefore, selects a range of elements along an axis. It can be helpful to read the expression ``arr2d[:2]`` as "select the first two rows of ``arr2d``:

In [138]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

![description](/Users/bmart231/DS/Notebooks/Numpy/indices.png)


## boolean indexing 

Let's consider an example where we have some data in an array and an array of names with duplicates:

In [139]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])

data = np.array([[4, 7], [0, 2], [-5, 6], [0,0], [1, 2], [-12, -4], [3, 4]])

In [140]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [141]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Suppose each name corresponds to a row in the  ``data`` array and we wanted to select all the rows with the corresponding name "Bob". Like arithmetic operations, comparisons (such as ==) with arrays are also vectorized. Thus, comparing ``names`` with the string "Bob" yields a Boolean array:

In [142]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

This boolean array can be passed when indexing the array:

In [143]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

The boolean array must be of the same length as the array axis it's indexing. You can even mix and match Boolean arrays with slices or integers (or sequences of integers)

In these examples, select from the rows where ``names`` == "Bob" and index the columns, too:

In [144]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [145]:
data[names == "Bob", 1]

array([7, 0])

To select everything but "Bob" you can either use != or negative the condition using ~: 

In [146]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [147]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [148]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

The ``~`` operator can be useful when you want to invert a Boolean array referenced by a variable:

In [149]:
cond = names == "Bob"

In [150]:
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

To select two of the three names to combine multiple Boolean conditions, use Boolean arithmetic operations like ``&`` (and) ``|`` (or):

In [151]:
mask = (names == "Bob") | (names == "Will")
    
mask

array([ True, False,  True,  True,  True, False, False])

In [152]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

Selecting data from an array by Boolean indexing and assigning the result to a new variable *always* creates a copy of the data, even if the returned array is unchanged. 

Setting values with Boolean arrays works by substituting the value or values on the righthand side into the locations where the Boolean array's value are ``True``. To set all of the negative values in ``data`` to 0, we need only do:

In [153]:
data[data < 0] = 0

data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

You can also set whole rows or columns using a one-dimensional Boolean array:

In [154]:
data[names != "Joe"] = 7

data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

## Fancy Indexing 

*Fancy Indexing* is a term adopted by NumPy to describe indexing using integer arrays. Suppose we had an 8 x 4 array:

In [155]:
arr = np.zeros((8, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [156]:
for i in range(8):
    arr[i] = i

arr    

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

To select a subset of the rows in a particular order, you can simply pass a list or ndarray of integers specifying the desired order:

In [157]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

Using negative indices selects rows from the end:

In [158]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

Passing multiple index arrays does something slightly different; it selects a one-dimensional array of elements corresponding to each tuple of indices:

In [159]:
arr = np.arange(32).reshape((8, 4))

arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [160]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

## Transposing Arrays and Swapping Axes

Transposing is a special form of reshaping that similarly returns a view on the underlying data without copying anything. Arrays have the ``transpose`` method and the special ``T`` attribute. 

In [163]:
arr = np.arange(15).reshape((3,5))

arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [164]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

When doing matrix computations, you may do this very often -- for example, when computing the inner matrix product using ``numpy.dot``

In [165]:
arr = np.array([[0,1,0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1,0,1]])

arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [166]:
np.dot(arr.T, arr)

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

The ``@`` infix operator is another way to do matrix multiplication:

In [167]:
arr.T @ arr

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

Simple transposing with ``.T`` is a special case of swapping axes.ndarry has the method ``swapaxes``, which takes a pair of axis numbers and switches the indicated axes to rearrage the data:

In [168]:
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [169]:
arr.swapaxes(0,1)

array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])